### ISSUE TITLE
Bug: Navigating by tab moves/removes characters

### ISSUE THREAD

**Issue by tmkarlsen** [otacke/h5p-crossword#14]
If I use tab to navigate back (shift + tab) and forth via the input fields, the character is moved to the left and finally dropped when they reach the start of the word.

**Comment by otacke** [comment]
@tmkarlsen Thanks! I just fixed that issue in https://github.com/otacke/h5p-crossword/commit/3de9f18d4310897ec2330c3dfb46063eed4a555f

**Comment by otacke** [comment]
@tmkarlsen The H5P core team has already released an update containing the fix today.

**Comment by tmkarlsen** [comment]
@otacke Thanks for the update. That is great news!
