### ISSUE TITLE
language support for version 0.4.9 on h5p.org

### ISSUE THREAD

**Issue by marcvanopstalndla** [otacke/h5p-crossword#37]
On 27-12-2021 Joubel installed version 0.4.9 of crosswords. The release summary included the remark "language updates". But it is still not possible to select Norwegian as language. Why is this language not available yet?

**Comment by otacke** [comment]
@marcvanopstalndla Joubel released from the release branch that doesn't contain all the changes from the master branch including the Norwegian translation.

**Comment by marcvanopstalndla** [comment]
@otacke , thanks for feedback
