### ISSUE TITLE
More background fit/scale options

### ISSUE THREAD

**Issue by e-me** [otacke/h5p-crossword#39]
Hello Oliver,

We'd like to ask if it is possible to implement more background fit/scale options besides fit to scale like `tile, stretch, span, etc`.

Kind regards.

**Comment by otacke** [comment]
@e-me Possible, sure. But I was merely the contractor for this content type, please see the [readme in this repository] (https://github.com/otacke/h5p-crossword/blob/master/README.md) and the [publishing blog post](https://www.olivertacke.de/labs/). You might want to reach out to LTC and ask whether they agree to have that feature.

**Comment by e-me** [comment]
Ok, I understand. Thanks for the reply!
