### ISSUE TITLE
Words with spaces written into the side panel give 0 points even if they are correct

### ISSUE THREAD

**Issue by falcon-git** [otacke/h5p-crossword#5]
As a learner I would like to get a point for typing in for instance "NEW YORK" in the side panel if "NEW YORK" is the correct answer so that I don't have to fill it directly into the crossword fields.

Steps to reproduce:

1. Make a crossword were one of the answers has a space in it
2. Answer the crossword via the side panel instead of in the crossword itself.
3. Observe that the word with the space in it won't be recognized as answered correctly.

**Comment by otacke** [comment]
@falcon-git Thanks, fixed!
