### ISSUE TITLE
inconsistency with clue and grid numbering

### ISSUE THREAD

**Issue by englishwebtls** [otacke/h5p-crossword#8]
Using Chrome on Mac OSX , 
When applying a limit to the number of clues I've noticed a problem with the numbering of the "Down" clues (see attachment). 
The numbering of the clues is not consistent with how they appear on the grid.
![crossword example 2](https://user-images.githubusercontent.com/26354396/130338903-d33ee210-382a-4b01-9ef2-b06425f52f2b.png)

**Comment by otacke** [comment]
@englishwebtls I'll check that, thanks!

**Comment by otacke** [comment]
@englishwebtls Found and fixed the problem. The H5P core team is about to release a new version with another slight improvement shortly.

**Comment by otacke** [comment]
@fnoks has just released the update with the fix.
